"""Train a synthetic CRP/IL-6 PINN for a competition/research PoC.

This training pipeline uses the synthetic inflammatory trajectories generated by
an ODE-based simulator. It is not clinically validated and must not be used for
diagnosis, treatment, or medical decision-making.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch import nn

from src.biotwin.models.biological_ode import BiologicalParameters
from src.biotwin.models.pinn import CRPIL6PINN, physics_loss


TRAINING_DATA_PATH = Path("data/synthetic/synthetic_inflammatory_trajectories.csv")


def load_trajectory_dataset(csv_path: str | Path = TRAINING_DATA_PATH) -> pd.DataFrame:
    """Load the synthetic trajectory dataset and validate the required columns."""
    dataset = pd.read_csv(csv_path)
    required = ["patient_id", "time_hours", "stimulus", "il6", "crp"]
    missing = [column for column in required if column not in dataset.columns]
    if missing:
        raise ValueError(f"Dataset is missing required columns: {missing}")
    return dataset


def patient_level_split(
    dataset: pd.DataFrame,
    validation_fraction: float = 0.2,
    seed: int = 42,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Split patients deterministically to avoid leaking a patient's trajectory across sets."""
    if not 0.0 < validation_fraction < 1.0:
        raise ValueError("validation_fraction must be between 0 and 1")
    rng = np.random.default_rng(seed)
    patients = dataset["patient_id"].drop_duplicates().to_numpy()
    rng.shuffle(patients)
    validation_count = max(1, int(np.floor(len(patients) * validation_fraction)))
    validation_patients = set(patients[:validation_count].tolist())
    train_mask = ~dataset["patient_id"].isin(validation_patients)
    validation_mask = dataset["patient_id"].isin(validation_patients)
    return dataset.loc[train_mask].reset_index(drop=True), dataset.loc[validation_mask].reset_index(drop=True)


def _tensorize(data: pd.DataFrame) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """Convert the required columns into CPU-friendly PyTorch tensors."""
    time = torch.tensor(data["time_hours"].to_numpy(dtype=np.float32), dtype=torch.float32)
    stimulus = torch.tensor(data["stimulus"].to_numpy(dtype=np.float32), dtype=torch.float32)
    targets_il6 = torch.tensor(data["il6"].to_numpy(dtype=np.float32), dtype=torch.float32)
    targets_crp = torch.tensor(data["crp"].to_numpy(dtype=np.float32), dtype=torch.float32)
    return time, stimulus, targets_il6, targets_crp


def data_loss_fn(predictions: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """Mean squared error on a per-output basis."""
    return torch.mean((predictions - targets) ** 2)


def train_pinn(
    model: nn.Module,
    train_data: tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor],
    params: BiologicalParameters,
    epochs: int = 5,
    learning_rate: float = 1e-3,
    physics_weight: float = 1.0,
    device: str = "cpu",
) -> tuple[nn.Module, list[dict[str, float]]]:
    """Train a PINN on CPU with a data-plus-physics loss using Adam."""
    if epochs <= 0:
        raise ValueError("epochs must be positive")
    if learning_rate <= 0:
        raise ValueError("learning_rate must be positive")
    if not isinstance(params, BiologicalParameters):
        raise ValueError("params must be a BiologicalParameters instance")

    time, stimulus, targets_il6, targets_crp = train_data
    time = time.to(device=device)
    stimulus = stimulus.to(device=device)
    targets_il6 = targets_il6.to(device=device)
    targets_crp = targets_crp.to(device=device)

    model = model.to(device=device)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    history: list[dict[str, float]] = []

    for epoch in range(1, epochs + 1):
        model.train()
        optimizer.zero_grad()
        predictions = model(torch.stack([time, stimulus], dim=1))
        data_term = data_loss_fn(predictions[:, 0], targets_il6) + data_loss_fn(predictions[:, 1], targets_crp)
        physics_term = physics_loss(model, time, stimulus, params)
        total_loss = data_term + physics_weight * physics_term

        total_loss.backward()
        optimizer.step()

        history.append(
            {
                "epoch": float(epoch),
                "total_loss": float(total_loss.detach().cpu()),
                "data_loss": float(data_term.detach().cpu()),
                "physics_loss": float(physics_term.detach().cpu()),
            }
        )

    return model, history


def main() -> None:
    """Run a small CPU smoke-training loop on a patient-subset of the synthetic data."""
    dataset = load_trajectory_dataset(TRAINING_DATA_PATH)
    train_df, validation_df = patient_level_split(dataset, validation_fraction=0.2, seed=42)
    patient_subset = train_df["patient_id"].drop_duplicates().head(10).tolist()
    train_subset = train_df[train_df["patient_id"].isin(patient_subset)].reset_index(drop=True)
    input_time, input_stimulus, target_il6, target_crp = _tensorize(train_subset)
    model = CRPIL6PINN(hidden_dim=16)
    params = BiologicalParameters(
        alpha_il6=1.8,
        k_il6=0.45,
        alpha_crp=1.2,
        k_crp=0.18,
    )
    train_data = (input_time, input_stimulus, target_il6, target_crp)
    trained_model, history = train_pinn(
        model=model,
        train_data=train_data,
        params=params,
        epochs=3,
        learning_rate=1e-3,
        physics_weight=1.0,
        device="cpu",
    )
    initial = history[0]
    final = history[-1]
    print("Training patients:", train_subset["patient_id"].nunique())
    print("Validation patients:", validation_df["patient_id"].nunique())
    print("Epochs: 3")
    print("Learning rate: 1e-3")
    print("Physics weight: 1.0")
    print(f"Initial total loss: {initial['total_loss']:.6f}")
    print(f"Final total loss: {final['total_loss']:.6f}")
    print(f"Initial data loss: {initial['data_loss']:.6f}")
    print(f"Final data loss: {final['data_loss']:.6f}")
    print(f"Initial physics loss: {initial['physics_loss']:.6f}")
    print(f"Final physics loss: {final['physics_loss']:.6f}")
    print("Losses finite:", all(np.isfinite([initial['total_loss'], final['total_loss'], initial['data_loss'], final['data_loss'], initial['physics_loss'], final['physics_loss']])) )
    print("Parameters changed:", any(param.detach().cpu().abs().sum().item() > 0.0 for param in trained_model.parameters()))


if __name__ == "__main__":
    main()
